version: "3.9"

services:
  # from: https://github.com/micahhausler/rabbitmq-compose/blob/master/docker-compose.yml
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    #   RABBITMQ_DEFAULT_USER: "rabbitmq"
    #   RABBITMQ_DEFAULT_PASS: "rabbitmq"
    #   RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"